spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_COLSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: embedded # 스키마 생성 시점
      table-prefix: SYSTEM_ # 쿼리 생성시 테이블 prefix
    job:
      names: ${job.name:NONE} # --job.name=job1,job2 와 같이 외부에서 실행할 배치job을 인자로 전달
      enabled: false # 스프링 배치 어플리케이션 실행시 job 자동 수행 block
